rvm: 2.4.0
env:
- PUPPET_GEM_VERSION=4.8.2
after_script: "bundle exec rake build"
before_deploy: "puppet module build"
deploy:
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: mpepping/puppet-filegen
